### ISSUE TITLE
In Terraform Registry, a pre-release is chosen as the latest version.

### ISSUE THREAD

**Issue by adezxc** [hashicorp/react-components#913]
In [function mapVersionList of remote-content.ts](https://github.com/hashicorp/react-components/blob/8316cb8caea7b4ebca3fbb6f413f2b63b10aa0cb/packages/docs-page/server/loaders/remote-content.ts#L79) pre-releases get chosen as the latest versions if their major/minor/patch is higher than other versions. From what I understand, it should be still the first in the version list, but the GA version should be labeled as `latest`. Image of the incorrect behavior: 
![image](https://user-images.githubusercontent.com/16798732/227328341-e4fa04a8-2c8a-4f8a-a62d-ce3b3e610bbe.png)

This may be intended, but it is unintuitive regarding to the docs of version constraining:
https://developer.hashicorp.com/terraform/language/expressions/version-constraints#version-constraint-behavior

**Comment by adezxc** [comment]
Reading more into the semver package, this might be due to Coerce truncating the pre-release suffix:

"This aims to provide a very forgiving translation of a non-semver string to semver. It looks for the first digit in a string, and consumes all remaining characters which satisfy at least a partial semver (e.g., 1, 1.2, 1.2.3) up to the max permitted length (256 characters). Longer versions are simply truncated (4.6.3.9.2-alpha2 becomes 4.6.3)."[1]

[1] - https://www.npmjs.com/package/semver

**Comment by adezxc** [comment]
This is a PR that I found that tackles a related issue on the Terraform website: 
https://github.com/hashicorp/dev-portal/pull/231

**Comment by rclark** [comment]
Hi @adezxc! 

> This may be intended, but it is unintuitive regarding to the docs of version constraining

Yeah, I agree with you. 

In trying to understand that piece of documentation, keep in mind that we have 2 different systems involved -- one is the Terraform Registry website, and the other is the Terraform CLI. Those docs are specifically about how the Terraform CLI will handle a configuration file.
- If there is no version constraint, the CLI will pick the latest non-prererelease version.
- If there is a version constraint that is inexact, the CLI will pick the latest, matching, non-prererelease version.
- If there is an exact version constraint, the CLI will pick a prerelease (if that's what was asked for).

But when we look at the Terraform Registry website today, listing prerelease versions as "latest" is the intended behavior _for that part of the system._ Changing this behavior on the website may affect other customers/partners who depend on or otherwise expect to see this existing behavior. We need to give that due consideration before making a change, and it may require external communications.

**Comment by adezxc** [comment]
Understood. Thank you for the quick response and confirming that it's intended. We'll take it into consideration moving forward, as we would like to continue with the beta releases, but this might be a setback.
